"""Foundation classes and functions for {PROJECT_NAME}"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/nbdev_notebook_template.ipynb.

# %% auto 0
__all__ = ['logger', 'DataModel', 'process_data', 'DataProcessor', 'summarize_collection']

# %% ../../nbs/nbdev_notebook_template.ipynb 3
# Core library imports - these will be exported to the Python module
from typing import Optional, List, Dict, Any, Union
from dataclasses import dataclass
from pathlib import Path
import logging

# %% ../../nbs/nbdev_notebook_template.ipynb 5
# Configure logging for the module
logger = logging.getLogger(__name__)

# %% ../../nbs/nbdev_notebook_template.ipynb 8
@dataclass
class DataModel:
    """
    Core data model representing {DESCRIPTION}.
    
    This class demonstrates:
    - Using dataclasses for clean data modeling
    - Type hints for clarity
    - Docstrings following Google/NumPy style
    
    Args:
        name: Human-readable identifier
        value: Numeric value associated with this item
        metadata: Optional dictionary for additional data
    
    Example:
        ```python
        item = DataModel(name="example", value=42)
        print(item.name)  # "example"
        ```
    """
    name: str
    value: float
    metadata: Optional[Dict[str, Any]] = None
    
    def __post_init__(self):
        """Validate data after initialization."""
        if not self.name:
            raise ValueError("name cannot be empty")
        if self.metadata is None:
            self.metadata = {}
    
    def is_positive(self) -> bool:
        """Check if value is positive."""
        return self.value > 0

# %% ../../nbs/nbdev_notebook_template.ipynb 12
def process_data(
    items: List[DataModel],
    threshold: float = 0.0,
    reverse: bool = False
) -> List[DataModel]:
    """
    Process a collection of data items with filtering and sorting.
    
    This function demonstrates:
    - Working with collections of custom objects
    - Configurable behavior via parameters
    - Clear documentation of processing logic
    
    Args:
        items: Collection of DataModel instances to process
        threshold: Minimum value to include (default: 0.0)
        reverse: Sort in descending order if True (default: False)
    
    Returns:
        Filtered and sorted list of DataModel instances
    
    Example:
        ```python
        items = [
            DataModel("a", 10.0),
            DataModel("b", -5.0),
            DataModel("c", 20.0)
        ]
        result = process_data(items, threshold=0.0)
        # Returns [DataModel("a", 10.0), DataModel("c", 20.0)]
        ```
    """
    # Filter based on threshold
    filtered = [item for item in items if item.value >= threshold]
    
    # Sort by value
    sorted_items = sorted(filtered, key=lambda x: x.value, reverse=reverse)
    
    logger.debug(f"Processed {len(items)} items -> {len(sorted_items)} results")
    
    return sorted_items

# %% ../../nbs/nbdev_notebook_template.ipynb 16
class DataProcessor:
    """
    Stateful processor for DataModel collections.
    
    This class demonstrates:
    - Object-oriented design patterns
    - Configuration management
    - State tracking
    
    Args:
        threshold: Default threshold for filtering
        auto_sort: Enable automatic sorting (default: True)
    
    Example:
        ```python
        processor = DataProcessor(threshold=5.0)
        items = [DataModel("a", 10), DataModel("b", 3)]
        result = processor.process(items)
        print(processor.stats)  # {'processed': 2, 'filtered': 1}
        ```
    """
    
    def __init__(self, threshold: float = 0.0, auto_sort: bool = True):
        self.threshold = threshold
        self.auto_sort = auto_sort
        self.stats = {'processed': 0, 'filtered': 0}
    
    def process(
        self, 
        items: List[DataModel], 
        threshold: Optional[float] = None
    ) -> List[DataModel]:
        """
        Process items using instance configuration.
        
        Args:
            items: Items to process
            threshold: Override instance threshold if provided
        
        Returns:
            Processed items
        """
        # Use instance threshold if not overridden
        thresh = threshold if threshold is not None else self.threshold
        
        # Update statistics
        self.stats['processed'] += len(items)
        
        # Filter
        result = [item for item in items if item.value >= thresh]
        self.stats['filtered'] += len(items) - len(result)
        
        # Sort if enabled
        if self.auto_sort:
            result = sorted(result, key=lambda x: x.value)
        
        return result
    
    def reset_stats(self):
        """Reset processing statistics."""
        self.stats = {'processed': 0, 'filtered': 0}

# %% ../../nbs/nbdev_notebook_template.ipynb 20
def summarize_collection(items: List[DataModel]) -> Dict[str, Any]:
    """
    Generate summary statistics for a collection.
    
    Args:
        items: Collection to summarize
    
    Returns:
        Dictionary with count, min, max, mean, and positive_count
    """
    if not items:
        return {
            'count': 0,
            'min': None,
            'max': None,
            'mean': None,
            'positive_count': 0
        }
    
    values = [item.value for item in items]
    
    return {
        'count': len(items),
        'min': min(values),
        'max': max(values),
        'mean': sum(values) / len(values),
        'positive_count': sum(1 for item in items if item.is_positive())
    }
